#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test5.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="V5")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void Insertdashveba(dashveba instance);
    partial void Updatedashveba(dashveba instance);
    partial void Deletedashveba(dashveba instance);
    partial void InsertAngGeg(AngGeg instance);
    partial void UpdateAngGeg(AngGeg instance);
    partial void DeleteAngGeg(AngGeg instance);
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void Insert_SawyisiNaSti(_SawyisiNaSti instance);
    partial void Update_SawyisiNaSti(_SawyisiNaSti instance);
    partial void Delete_SawyisiNaSti(_SawyisiNaSti instance);
    partial void Insert_BugaltruliGatareba(_BugaltruliGatareba instance);
    partial void Update_BugaltruliGatareba(_BugaltruliGatareba instance);
    partial void Delete_BugaltruliGatareba(_BugaltruliGatareba instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["V5ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<dashveba> dashvebas
		{
			get
			{
				return this.GetTable<dashveba>();
			}
		}
		
		public System.Data.Linq.Table<AngGeg> AngGegs
		{
			get
			{
				return this.GetTable<AngGeg>();
			}
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<_SawyisiNaSti> _SawyisiNaStis
		{
			get
			{
				return this.GetTable<_SawyisiNaSti>();
			}
		}
		
		public System.Data.Linq.Table<_BugaltruliGatareba> _BugaltruliGatarebas
		{
			get
			{
				return this.GetTable<_BugaltruliGatareba>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_SawN]")]
		public ISingleResult<_SawNResult> _SawN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SawT", DbType="Date")] System.Nullable<System.DateTime> sawT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SabT", DbType="Date")] System.Nullable<System.DateTime> sabT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comp", DbType="Int")] System.Nullable<int> comp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sawT, sabT, comp);
			return ((ISingleResult<_SawNResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.list4")]
		public ISingleResult<list4Result> list4([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<list4Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ang")]
		public ISingleResult<AngResult> Ang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Com", DbType="Int")] System.Nullable<int> com)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), com);
			return ((ISingleResult<AngResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[_BugGat]")]
		public ISingleResult<_BugGatResult> _BugGat([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> com)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), com);
			return ((ISingleResult<_BugGatResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Mail;
		
		private int _Company;
		
		private System.DateTime _Tarigi;
		
		private string _Pass;
		
		private int _Dashveba;
		
		private EntitySet<AngGeg> _AngGegs;
		
		private EntitySet<_SawyisiNaSti> @__SawyisiNaStis;
		
		private EntitySet<_BugaltruliGatareba> @__BugaltruliGatarebas;
		
		private EntityRef<dashveba> _dashveba1;
		
		private EntityRef<Company> _Company1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnCompanyChanging(int value);
    partial void OnCompanyChanged();
    partial void OnTarigiChanging(System.DateTime value);
    partial void OnTarigiChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnDashvebaChanging(int value);
    partial void OnDashvebaChanged();
    #endregion
		
		public User()
		{
			this._AngGegs = new EntitySet<AngGeg>(new Action<AngGeg>(this.attach_AngGegs), new Action<AngGeg>(this.detach_AngGegs));
			this.@__SawyisiNaStis = new EntitySet<_SawyisiNaSti>(new Action<_SawyisiNaSti>(this.attach__SawyisiNaStis), new Action<_SawyisiNaSti>(this.detach__SawyisiNaStis));
			this.@__BugaltruliGatarebas = new EntitySet<_BugaltruliGatareba>(new Action<_BugaltruliGatareba>(this.attach__BugaltruliGatarebas), new Action<_BugaltruliGatareba>(this.detach__BugaltruliGatarebas));
			this._dashveba1 = default(EntityRef<dashveba>);
			this._Company1 = default(EntityRef<Company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="Int NOT NULL")]
		public int Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					if (this._Company1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarigi", DbType="Date NOT NULL")]
		public System.DateTime Tarigi
		{
			get
			{
				return this._Tarigi;
			}
			set
			{
				if ((this._Tarigi != value))
				{
					this.OnTarigiChanging(value);
					this.SendPropertyChanging();
					this._Tarigi = value;
					this.SendPropertyChanged("Tarigi");
					this.OnTarigiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dashveba", DbType="Int NOT NULL")]
		public int Dashveba
		{
			get
			{
				return this._Dashveba;
			}
			set
			{
				if ((this._Dashveba != value))
				{
					if (this._dashveba1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDashvebaChanging(value);
					this.SendPropertyChanging();
					this._Dashveba = value;
					this.SendPropertyChanged("Dashveba");
					this.OnDashvebaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_AngGeg", Storage="_AngGegs", ThisKey="Id", OtherKey="User")]
		public EntitySet<AngGeg> AngGegs
		{
			get
			{
				return this._AngGegs;
			}
			set
			{
				this._AngGegs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User__SawyisiNaSti", Storage="__SawyisiNaStis", ThisKey="Id", OtherKey="User")]
		public EntitySet<_SawyisiNaSti> _SawyisiNaStis
		{
			get
			{
				return this.@__SawyisiNaStis;
			}
			set
			{
				this.@__SawyisiNaStis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User__BugaltruliGatareba", Storage="__BugaltruliGatarebas", ThisKey="Id", OtherKey="Shemsrulebeli")]
		public EntitySet<_BugaltruliGatareba> _BugaltruliGatarebas
		{
			get
			{
				return this.@__BugaltruliGatarebas;
			}
			set
			{
				this.@__BugaltruliGatarebas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dashveba_User", Storage="_dashveba1", ThisKey="Dashveba", OtherKey="Id", IsForeignKey=true)]
		public dashveba dashveba1
		{
			get
			{
				return this._dashveba1.Entity;
			}
			set
			{
				dashveba previousValue = this._dashveba1.Entity;
				if (((previousValue != value) 
							|| (this._dashveba1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dashveba1.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._dashveba1.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._Dashveba = value.Id;
					}
					else
					{
						this._Dashveba = default(int);
					}
					this.SendPropertyChanged("dashveba1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_User", Storage="_Company1", ThisKey="Company", OtherKey="Id", IsForeignKey=true)]
		public Company Company1
		{
			get
			{
				return this._Company1.Entity;
			}
			set
			{
				Company previousValue = this._Company1.Entity;
				if (((previousValue != value) 
							|| (this._Company1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Company1.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Company1.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._Company = value.Id;
					}
					else
					{
						this._Company = default(int);
					}
					this.SendPropertyChanged("Company1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AngGegs(AngGeg entity)
		{
			this.SendPropertyChanging();
			entity.User1 = this;
		}
		
		private void detach_AngGegs(AngGeg entity)
		{
			this.SendPropertyChanging();
			entity.User1 = null;
		}
		
		private void attach__SawyisiNaStis(_SawyisiNaSti entity)
		{
			this.SendPropertyChanging();
			entity.User1 = this;
		}
		
		private void detach__SawyisiNaStis(_SawyisiNaSti entity)
		{
			this.SendPropertyChanging();
			entity.User1 = null;
		}
		
		private void attach__BugaltruliGatarebas(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach__BugaltruliGatarebas(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dashveba")]
	public partial class dashveba : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Status;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public dashveba()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dashveba_User", Storage="_Users", ThisKey="Id", OtherKey="Dashveba")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.dashveba1 = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.dashveba1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AngGeg")]
	public partial class AngGeg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PID;
		
		private int _DONE;
		
		private string _ANGNOM;
		
		private string _ANDDAS;
		
		private string _ANGTIP;
		
		private bool _GADAF;
		
		private string _VALUTA;
		
		private System.Nullable<int> _Compani;
		
		private System.Nullable<int> _User;
		
		private EntitySet<_SawyisiNaSti> @__SawyisiNaStis;
		
		private EntitySet<_BugaltruliGatareba> @__BugaltruliGatarebas;
		
		private EntitySet<_BugaltruliGatareba> @__BugaltruliGatarebas1;
		
		private EntityRef<User> _User1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPIDChanging(int value);
    partial void OnPIDChanged();
    partial void OnDONEChanging(int value);
    partial void OnDONEChanged();
    partial void OnANGNOMChanging(string value);
    partial void OnANGNOMChanged();
    partial void OnANDDASChanging(string value);
    partial void OnANDDASChanged();
    partial void OnANGTIPChanging(string value);
    partial void OnANGTIPChanged();
    partial void OnGADAFChanging(bool value);
    partial void OnGADAFChanged();
    partial void OnVALUTAChanging(string value);
    partial void OnVALUTAChanged();
    partial void OnCompaniChanging(System.Nullable<int> value);
    partial void OnCompaniChanged();
    partial void OnUserChanging(System.Nullable<int> value);
    partial void OnUserChanged();
    #endregion
		
		public AngGeg()
		{
			this.@__SawyisiNaStis = new EntitySet<_SawyisiNaSti>(new Action<_SawyisiNaSti>(this.attach__SawyisiNaStis), new Action<_SawyisiNaSti>(this.detach__SawyisiNaStis));
			this.@__BugaltruliGatarebas = new EntitySet<_BugaltruliGatareba>(new Action<_BugaltruliGatareba>(this.attach__BugaltruliGatarebas), new Action<_BugaltruliGatareba>(this.detach__BugaltruliGatarebas));
			this.@__BugaltruliGatarebas1 = new EntitySet<_BugaltruliGatareba>(new Action<_BugaltruliGatareba>(this.attach__BugaltruliGatarebas1), new Action<_BugaltruliGatareba>(this.detach__BugaltruliGatarebas1));
			this._User1 = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int NOT NULL")]
		public int PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONE", DbType="Int NOT NULL")]
		public int DONE
		{
			get
			{
				return this._DONE;
			}
			set
			{
				if ((this._DONE != value))
				{
					this.OnDONEChanging(value);
					this.SendPropertyChanging();
					this._DONE = value;
					this.SendPropertyChanged("DONE");
					this.OnDONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANGNOM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANGNOM
		{
			get
			{
				return this._ANGNOM;
			}
			set
			{
				if ((this._ANGNOM != value))
				{
					this.OnANGNOMChanging(value);
					this.SendPropertyChanging();
					this._ANGNOM = value;
					this.SendPropertyChanged("ANGNOM");
					this.OnANGNOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANDDAS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANDDAS
		{
			get
			{
				return this._ANDDAS;
			}
			set
			{
				if ((this._ANDDAS != value))
				{
					this.OnANDDASChanging(value);
					this.SendPropertyChanging();
					this._ANDDAS = value;
					this.SendPropertyChanged("ANDDAS");
					this.OnANDDASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANGTIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANGTIP
		{
			get
			{
				return this._ANGTIP;
			}
			set
			{
				if ((this._ANGTIP != value))
				{
					this.OnANGTIPChanging(value);
					this.SendPropertyChanging();
					this._ANGTIP = value;
					this.SendPropertyChanged("ANGTIP");
					this.OnANGTIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GADAF", DbType="Bit NOT NULL")]
		public bool GADAF
		{
			get
			{
				return this._GADAF;
			}
			set
			{
				if ((this._GADAF != value))
				{
					this.OnGADAFChanging(value);
					this.SendPropertyChanging();
					this._GADAF = value;
					this.SendPropertyChanged("GADAF");
					this.OnGADAFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUTA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string VALUTA
		{
			get
			{
				return this._VALUTA;
			}
			set
			{
				if ((this._VALUTA != value))
				{
					this.OnVALUTAChanging(value);
					this.SendPropertyChanging();
					this._VALUTA = value;
					this.SendPropertyChanged("VALUTA");
					this.OnVALUTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compani", DbType="Int")]
		public System.Nullable<int> Compani
		{
			get
			{
				return this._Compani;
			}
			set
			{
				if ((this._Compani != value))
				{
					this.OnCompaniChanging(value);
					this.SendPropertyChanging();
					this._Compani = value;
					this.SendPropertyChanged("Compani");
					this.OnCompaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="Int")]
		public System.Nullable<int> User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AngGeg__SawyisiNaSti", Storage="__SawyisiNaStis", ThisKey="ID", OtherKey="AngNom")]
		public EntitySet<_SawyisiNaSti> _SawyisiNaStis
		{
			get
			{
				return this.@__SawyisiNaStis;
			}
			set
			{
				this.@__SawyisiNaStis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AngGeg__BugaltruliGatareba", Storage="__BugaltruliGatarebas", ThisKey="ID", OtherKey="DebAng")]
		public EntitySet<_BugaltruliGatareba> _BugaltruliGatarebas
		{
			get
			{
				return this.@__BugaltruliGatarebas;
			}
			set
			{
				this.@__BugaltruliGatarebas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AngGeg__BugaltruliGatareba1", Storage="__BugaltruliGatarebas1", ThisKey="ID", OtherKey="KredAng")]
		public EntitySet<_BugaltruliGatareba> _BugaltruliGatarebas1
		{
			get
			{
				return this.@__BugaltruliGatarebas1;
			}
			set
			{
				this.@__BugaltruliGatarebas1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_AngGeg", Storage="_User1", ThisKey="User", OtherKey="Id", IsForeignKey=true)]
		public User User1
		{
			get
			{
				return this._User1.Entity;
			}
			set
			{
				User previousValue = this._User1.Entity;
				if (((previousValue != value) 
							|| (this._User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User1.Entity = null;
						previousValue.AngGegs.Remove(this);
					}
					this._User1.Entity = value;
					if ((value != null))
					{
						value.AngGegs.Add(this);
						this._User = value.Id;
					}
					else
					{
						this._User = default(Nullable<int>);
					}
					this.SendPropertyChanged("User1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach__SawyisiNaStis(_SawyisiNaSti entity)
		{
			this.SendPropertyChanging();
			entity.AngGeg = this;
		}
		
		private void detach__SawyisiNaStis(_SawyisiNaSti entity)
		{
			this.SendPropertyChanging();
			entity.AngGeg = null;
		}
		
		private void attach__BugaltruliGatarebas(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.AngGeg = this;
		}
		
		private void detach__BugaltruliGatarebas(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.AngGeg = null;
		}
		
		private void attach__BugaltruliGatarebas1(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.AngGeg1 = this;
		}
		
		private void detach__BugaltruliGatarebas1(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.AngGeg1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Company1;
		
		private int _UserC;
		
		private System.Nullable<int> _SasNashti;
		
		private EntitySet<User> _Users;
		
		private EntitySet<_SawyisiNaSti> @__SawyisiNaStis;
		
		private EntitySet<_BugaltruliGatareba> @__BugaltruliGatarebas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCompany1Changing(string value);
    partial void OnCompany1Changed();
    partial void OnUserCChanging(int value);
    partial void OnUserCChanged();
    partial void OnSasNashtiChanging(System.Nullable<int> value);
    partial void OnSasNashtiChanged();
    #endregion
		
		public Company()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			this.@__SawyisiNaStis = new EntitySet<_SawyisiNaSti>(new Action<_SawyisiNaSti>(this.attach__SawyisiNaStis), new Action<_SawyisiNaSti>(this.detach__SawyisiNaStis));
			this.@__BugaltruliGatarebas = new EntitySet<_BugaltruliGatareba>(new Action<_BugaltruliGatareba>(this.attach__BugaltruliGatarebas), new Action<_BugaltruliGatareba>(this.detach__BugaltruliGatarebas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Company", Storage="_Company1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Company1
		{
			get
			{
				return this._Company1;
			}
			set
			{
				if ((this._Company1 != value))
				{
					this.OnCompany1Changing(value);
					this.SendPropertyChanging();
					this._Company1 = value;
					this.SendPropertyChanged("Company1");
					this.OnCompany1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserC", DbType="Int NOT NULL")]
		public int UserC
		{
			get
			{
				return this._UserC;
			}
			set
			{
				if ((this._UserC != value))
				{
					this.OnUserCChanging(value);
					this.SendPropertyChanging();
					this._UserC = value;
					this.SendPropertyChanged("UserC");
					this.OnUserCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SasNashti", DbType="Int")]
		public System.Nullable<int> SasNashti
		{
			get
			{
				return this._SasNashti;
			}
			set
			{
				if ((this._SasNashti != value))
				{
					this.OnSasNashtiChanging(value);
					this.SendPropertyChanging();
					this._SasNashti = value;
					this.SendPropertyChanged("SasNashti");
					this.OnSasNashtiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_User", Storage="_Users", ThisKey="Id", OtherKey="Company")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company__SawyisiNaSti", Storage="__SawyisiNaStis", ThisKey="Id", OtherKey="Company")]
		public EntitySet<_SawyisiNaSti> _SawyisiNaStis
		{
			get
			{
				return this.@__SawyisiNaStis;
			}
			set
			{
				this.@__SawyisiNaStis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company__BugaltruliGatareba", Storage="__BugaltruliGatarebas", ThisKey="Id", OtherKey="company")]
		public EntitySet<_BugaltruliGatareba> _BugaltruliGatarebas
		{
			get
			{
				return this.@__BugaltruliGatarebas;
			}
			set
			{
				this.@__BugaltruliGatarebas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Company1 = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Company1 = null;
		}
		
		private void attach__SawyisiNaStis(_SawyisiNaSti entity)
		{
			this.SendPropertyChanging();
			entity.Company1 = this;
		}
		
		private void detach__SawyisiNaStis(_SawyisiNaSti entity)
		{
			this.SendPropertyChanging();
			entity.Company1 = null;
		}
		
		private void attach__BugaltruliGatarebas(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.Company1 = this;
		}
		
		private void detach__BugaltruliGatarebas(_BugaltruliGatareba entity)
		{
			this.SendPropertyChanging();
			entity.Company1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_SawyisiNaSti]")]
	public partial class _SawyisiNaSti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _AngNom;
		
		private System.Nullable<int> _Debeti;
		
		private System.Nullable<int> _Krediti;
		
		private System.Nullable<System.DateTime> _SasNaStDate;
		
		private int _Company;
		
		private int _User;
		
		private EntityRef<AngGeg> _AngGeg;
		
		private EntityRef<Company> _Company1;
		
		private EntityRef<User> _User1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnAngNomChanging(int value);
    partial void OnAngNomChanged();
    partial void OnDebetiChanging(System.Nullable<int> value);
    partial void OnDebetiChanged();
    partial void OnKreditiChanging(System.Nullable<int> value);
    partial void OnKreditiChanged();
    partial void OnSasNaStDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSasNaStDateChanged();
    partial void OnCompanyChanging(int value);
    partial void OnCompanyChanged();
    partial void OnUserChanging(int value);
    partial void OnUserChanged();
    #endregion
		
		public _SawyisiNaSti()
		{
			this._AngGeg = default(EntityRef<AngGeg>);
			this._Company1 = default(EntityRef<Company>);
			this._User1 = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AngNom", DbType="Int NOT NULL")]
		public int AngNom
		{
			get
			{
				return this._AngNom;
			}
			set
			{
				if ((this._AngNom != value))
				{
					if (this._AngGeg.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAngNomChanging(value);
					this.SendPropertyChanging();
					this._AngNom = value;
					this.SendPropertyChanged("AngNom");
					this.OnAngNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debeti", DbType="Int")]
		public System.Nullable<int> Debeti
		{
			get
			{
				return this._Debeti;
			}
			set
			{
				if ((this._Debeti != value))
				{
					this.OnDebetiChanging(value);
					this.SendPropertyChanging();
					this._Debeti = value;
					this.SendPropertyChanged("Debeti");
					this.OnDebetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Krediti", DbType="Int")]
		public System.Nullable<int> Krediti
		{
			get
			{
				return this._Krediti;
			}
			set
			{
				if ((this._Krediti != value))
				{
					this.OnKreditiChanging(value);
					this.SendPropertyChanging();
					this._Krediti = value;
					this.SendPropertyChanged("Krediti");
					this.OnKreditiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SasNaStDate", DbType="Date")]
		public System.Nullable<System.DateTime> SasNaStDate
		{
			get
			{
				return this._SasNaStDate;
			}
			set
			{
				if ((this._SasNaStDate != value))
				{
					this.OnSasNaStDateChanging(value);
					this.SendPropertyChanging();
					this._SasNaStDate = value;
					this.SendPropertyChanged("SasNaStDate");
					this.OnSasNaStDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="Int NOT NULL")]
		public int Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					if (this._Company1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="Int NOT NULL")]
		public int User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AngGeg__SawyisiNaSti", Storage="_AngGeg", ThisKey="AngNom", OtherKey="ID", IsForeignKey=true)]
		public AngGeg AngGeg
		{
			get
			{
				return this._AngGeg.Entity;
			}
			set
			{
				AngGeg previousValue = this._AngGeg.Entity;
				if (((previousValue != value) 
							|| (this._AngGeg.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AngGeg.Entity = null;
						previousValue._SawyisiNaStis.Remove(this);
					}
					this._AngGeg.Entity = value;
					if ((value != null))
					{
						value._SawyisiNaStis.Add(this);
						this._AngNom = value.ID;
					}
					else
					{
						this._AngNom = default(int);
					}
					this.SendPropertyChanged("AngGeg");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company__SawyisiNaSti", Storage="_Company1", ThisKey="Company", OtherKey="Id", IsForeignKey=true)]
		public Company Company1
		{
			get
			{
				return this._Company1.Entity;
			}
			set
			{
				Company previousValue = this._Company1.Entity;
				if (((previousValue != value) 
							|| (this._Company1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Company1.Entity = null;
						previousValue._SawyisiNaStis.Remove(this);
					}
					this._Company1.Entity = value;
					if ((value != null))
					{
						value._SawyisiNaStis.Add(this);
						this._Company = value.Id;
					}
					else
					{
						this._Company = default(int);
					}
					this.SendPropertyChanged("Company1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User__SawyisiNaSti", Storage="_User1", ThisKey="User", OtherKey="Id", IsForeignKey=true)]
		public User User1
		{
			get
			{
				return this._User1.Entity;
			}
			set
			{
				User previousValue = this._User1.Entity;
				if (((previousValue != value) 
							|| (this._User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User1.Entity = null;
						previousValue._SawyisiNaStis.Remove(this);
					}
					this._User1.Entity = value;
					if ((value != null))
					{
						value._SawyisiNaStis.Add(this);
						this._User = value.Id;
					}
					else
					{
						this._User = default(int);
					}
					this.SendPropertyChanged("User1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_BugaltruliGatareba]")]
	public partial class _BugaltruliGatareba : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private bool _Dadasturebuli;
		
		private bool _Gadadebuli;
		
		private int _DokTipi;
		
		private int _DokNom;
		
		private System.DateTime _Tarigi;
		
		private int _DebAng;
		
		private int _KredAng;
		
		private System.Nullable<int> _Tanxa;
		
		private double _Kursi;
		
		private System.Nullable<int> _Memoriali;
		
		private string _Safudzveli;
		
		private string _AnalizuriVeli;
		
		private System.DateTime _ShesrulebisTarigi;
		
		private int _company;
		
		private int _Shemsrulebeli;
		
		private EntityRef<AngGeg> _AngGeg;
		
		private EntityRef<AngGeg> _AngGeg1;
		
		private EntityRef<Company> _Company1;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDadasturebuliChanging(bool value);
    partial void OnDadasturebuliChanged();
    partial void OnGadadebuliChanging(bool value);
    partial void OnGadadebuliChanged();
    partial void OnDokTipiChanging(int value);
    partial void OnDokTipiChanged();
    partial void OnDokNomChanging(int value);
    partial void OnDokNomChanged();
    partial void OnTarigiChanging(System.DateTime value);
    partial void OnTarigiChanged();
    partial void OnDebAngChanging(int value);
    partial void OnDebAngChanged();
    partial void OnKredAngChanging(int value);
    partial void OnKredAngChanged();
    partial void OnTanxaChanging(System.Nullable<int> value);
    partial void OnTanxaChanged();
    partial void OnKursiChanging(double value);
    partial void OnKursiChanged();
    partial void OnMemorialiChanging(System.Nullable<int> value);
    partial void OnMemorialiChanged();
    partial void OnSafudzveliChanging(string value);
    partial void OnSafudzveliChanged();
    partial void OnAnalizuriVeliChanging(string value);
    partial void OnAnalizuriVeliChanged();
    partial void OnShesrulebisTarigiChanging(System.DateTime value);
    partial void OnShesrulebisTarigiChanged();
    partial void OncompanyChanging(int value);
    partial void OncompanyChanged();
    partial void OnShemsrulebeliChanging(int value);
    partial void OnShemsrulebeliChanged();
    #endregion
		
		public _BugaltruliGatareba()
		{
			this._AngGeg = default(EntityRef<AngGeg>);
			this._AngGeg1 = default(EntityRef<AngGeg>);
			this._Company1 = default(EntityRef<Company>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dadasturebuli", DbType="Bit NOT NULL")]
		public bool Dadasturebuli
		{
			get
			{
				return this._Dadasturebuli;
			}
			set
			{
				if ((this._Dadasturebuli != value))
				{
					this.OnDadasturebuliChanging(value);
					this.SendPropertyChanging();
					this._Dadasturebuli = value;
					this.SendPropertyChanged("Dadasturebuli");
					this.OnDadasturebuliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gadadebuli", DbType="Bit NOT NULL")]
		public bool Gadadebuli
		{
			get
			{
				return this._Gadadebuli;
			}
			set
			{
				if ((this._Gadadebuli != value))
				{
					this.OnGadadebuliChanging(value);
					this.SendPropertyChanging();
					this._Gadadebuli = value;
					this.SendPropertyChanged("Gadadebuli");
					this.OnGadadebuliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DokTipi", DbType="Int NOT NULL")]
		public int DokTipi
		{
			get
			{
				return this._DokTipi;
			}
			set
			{
				if ((this._DokTipi != value))
				{
					this.OnDokTipiChanging(value);
					this.SendPropertyChanging();
					this._DokTipi = value;
					this.SendPropertyChanged("DokTipi");
					this.OnDokTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DokNom", DbType="Int NOT NULL")]
		public int DokNom
		{
			get
			{
				return this._DokNom;
			}
			set
			{
				if ((this._DokNom != value))
				{
					this.OnDokNomChanging(value);
					this.SendPropertyChanging();
					this._DokNom = value;
					this.SendPropertyChanged("DokNom");
					this.OnDokNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarigi", DbType="Date NOT NULL")]
		public System.DateTime Tarigi
		{
			get
			{
				return this._Tarigi;
			}
			set
			{
				if ((this._Tarigi != value))
				{
					this.OnTarigiChanging(value);
					this.SendPropertyChanging();
					this._Tarigi = value;
					this.SendPropertyChanged("Tarigi");
					this.OnTarigiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebAng", DbType="Int NOT NULL")]
		public int DebAng
		{
			get
			{
				return this._DebAng;
			}
			set
			{
				if ((this._DebAng != value))
				{
					if (this._AngGeg.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDebAngChanging(value);
					this.SendPropertyChanging();
					this._DebAng = value;
					this.SendPropertyChanged("DebAng");
					this.OnDebAngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KredAng", DbType="Int NOT NULL")]
		public int KredAng
		{
			get
			{
				return this._KredAng;
			}
			set
			{
				if ((this._KredAng != value))
				{
					if (this._AngGeg1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKredAngChanging(value);
					this.SendPropertyChanging();
					this._KredAng = value;
					this.SendPropertyChanged("KredAng");
					this.OnKredAngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanxa", DbType="Int")]
		public System.Nullable<int> Tanxa
		{
			get
			{
				return this._Tanxa;
			}
			set
			{
				if ((this._Tanxa != value))
				{
					this.OnTanxaChanging(value);
					this.SendPropertyChanging();
					this._Tanxa = value;
					this.SendPropertyChanged("Tanxa");
					this.OnTanxaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kursi", DbType="Float NOT NULL")]
		public double Kursi
		{
			get
			{
				return this._Kursi;
			}
			set
			{
				if ((this._Kursi != value))
				{
					this.OnKursiChanging(value);
					this.SendPropertyChanging();
					this._Kursi = value;
					this.SendPropertyChanged("Kursi");
					this.OnKursiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memoriali", DbType="Int")]
		public System.Nullable<int> Memoriali
		{
			get
			{
				return this._Memoriali;
			}
			set
			{
				if ((this._Memoriali != value))
				{
					this.OnMemorialiChanging(value);
					this.SendPropertyChanging();
					this._Memoriali = value;
					this.SendPropertyChanged("Memoriali");
					this.OnMemorialiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Safudzveli", DbType="NVarChar(1000)")]
		public string Safudzveli
		{
			get
			{
				return this._Safudzveli;
			}
			set
			{
				if ((this._Safudzveli != value))
				{
					this.OnSafudzveliChanging(value);
					this.SendPropertyChanging();
					this._Safudzveli = value;
					this.SendPropertyChanged("Safudzveli");
					this.OnSafudzveliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalizuriVeli", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AnalizuriVeli
		{
			get
			{
				return this._AnalizuriVeli;
			}
			set
			{
				if ((this._AnalizuriVeli != value))
				{
					this.OnAnalizuriVeliChanging(value);
					this.SendPropertyChanging();
					this._AnalizuriVeli = value;
					this.SendPropertyChanged("AnalizuriVeli");
					this.OnAnalizuriVeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShesrulebisTarigi", DbType="Date NOT NULL")]
		public System.DateTime ShesrulebisTarigi
		{
			get
			{
				return this._ShesrulebisTarigi;
			}
			set
			{
				if ((this._ShesrulebisTarigi != value))
				{
					this.OnShesrulebisTarigiChanging(value);
					this.SendPropertyChanging();
					this._ShesrulebisTarigi = value;
					this.SendPropertyChanged("ShesrulebisTarigi");
					this.OnShesrulebisTarigiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="Int NOT NULL")]
		public int company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					if (this._Company1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shemsrulebeli", DbType="Int NOT NULL")]
		public int Shemsrulebeli
		{
			get
			{
				return this._Shemsrulebeli;
			}
			set
			{
				if ((this._Shemsrulebeli != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShemsrulebeliChanging(value);
					this.SendPropertyChanging();
					this._Shemsrulebeli = value;
					this.SendPropertyChanged("Shemsrulebeli");
					this.OnShemsrulebeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AngGeg__BugaltruliGatareba", Storage="_AngGeg", ThisKey="DebAng", OtherKey="ID", IsForeignKey=true)]
		public AngGeg AngGeg
		{
			get
			{
				return this._AngGeg.Entity;
			}
			set
			{
				AngGeg previousValue = this._AngGeg.Entity;
				if (((previousValue != value) 
							|| (this._AngGeg.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AngGeg.Entity = null;
						previousValue._BugaltruliGatarebas.Remove(this);
					}
					this._AngGeg.Entity = value;
					if ((value != null))
					{
						value._BugaltruliGatarebas.Add(this);
						this._DebAng = value.ID;
					}
					else
					{
						this._DebAng = default(int);
					}
					this.SendPropertyChanged("AngGeg");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AngGeg__BugaltruliGatareba1", Storage="_AngGeg1", ThisKey="KredAng", OtherKey="ID", IsForeignKey=true)]
		public AngGeg AngGeg1
		{
			get
			{
				return this._AngGeg1.Entity;
			}
			set
			{
				AngGeg previousValue = this._AngGeg1.Entity;
				if (((previousValue != value) 
							|| (this._AngGeg1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AngGeg1.Entity = null;
						previousValue._BugaltruliGatarebas1.Remove(this);
					}
					this._AngGeg1.Entity = value;
					if ((value != null))
					{
						value._BugaltruliGatarebas1.Add(this);
						this._KredAng = value.ID;
					}
					else
					{
						this._KredAng = default(int);
					}
					this.SendPropertyChanged("AngGeg1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company__BugaltruliGatareba", Storage="_Company1", ThisKey="company", OtherKey="Id", IsForeignKey=true)]
		public Company Company1
		{
			get
			{
				return this._Company1.Entity;
			}
			set
			{
				Company previousValue = this._Company1.Entity;
				if (((previousValue != value) 
							|| (this._Company1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Company1.Entity = null;
						previousValue._BugaltruliGatarebas.Remove(this);
					}
					this._Company1.Entity = value;
					if ((value != null))
					{
						value._BugaltruliGatarebas.Add(this);
						this._company = value.Id;
					}
					else
					{
						this._company = default(int);
					}
					this.SendPropertyChanged("Company1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User__BugaltruliGatareba", Storage="_User", ThisKey="Shemsrulebeli", OtherKey="Id", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue._BugaltruliGatarebas.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value._BugaltruliGatarebas.Add(this);
						this._Shemsrulebeli = value.Id;
					}
					else
					{
						this._Shemsrulebeli = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class _SawNResult
	{
		
		private System.Nullable<int> _nashti;
		
		public _SawNResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nashti", DbType="Int")]
		public System.Nullable<int> nashti
		{
			get
			{
				return this._nashti;
			}
			set
			{
				if ((this._nashti != value))
				{
					this._nashti = value;
				}
			}
		}
	}
	
	public partial class list4Result
	{
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<int> _PID;
		
		private System.Nullable<int> _DONE;
		
		private string _ANGNOM;
		
		private string _ANDDAS;
		
		private string _ANGTIP;
		
		private System.Nullable<bool> _GADAF;
		
		private System.Nullable<int> _Debeti;
		
		private System.Nullable<int> _krediti;
		
		private string _VALUTA;
		
		private System.Nullable<System.DateTime> _SasNaStDate;
		
		private System.Nullable<int> _Compani;
		
		private System.Nullable<int> _User;
		
		public list4Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int")]
		public System.Nullable<int> PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this._PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONE", DbType="Int")]
		public System.Nullable<int> DONE
		{
			get
			{
				return this._DONE;
			}
			set
			{
				if ((this._DONE != value))
				{
					this._DONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANGNOM", DbType="VarChar(50)")]
		public string ANGNOM
		{
			get
			{
				return this._ANGNOM;
			}
			set
			{
				if ((this._ANGNOM != value))
				{
					this._ANGNOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANDDAS", DbType="VarChar(50)")]
		public string ANDDAS
		{
			get
			{
				return this._ANDDAS;
			}
			set
			{
				if ((this._ANDDAS != value))
				{
					this._ANDDAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANGTIP", DbType="VarChar(50)")]
		public string ANGTIP
		{
			get
			{
				return this._ANGTIP;
			}
			set
			{
				if ((this._ANGTIP != value))
				{
					this._ANGTIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GADAF", DbType="Bit")]
		public System.Nullable<bool> GADAF
		{
			get
			{
				return this._GADAF;
			}
			set
			{
				if ((this._GADAF != value))
				{
					this._GADAF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debeti", DbType="Int")]
		public System.Nullable<int> Debeti
		{
			get
			{
				return this._Debeti;
			}
			set
			{
				if ((this._Debeti != value))
				{
					this._Debeti = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_krediti", DbType="Int")]
		public System.Nullable<int> krediti
		{
			get
			{
				return this._krediti;
			}
			set
			{
				if ((this._krediti != value))
				{
					this._krediti = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUTA", DbType="VarChar(50)")]
		public string VALUTA
		{
			get
			{
				return this._VALUTA;
			}
			set
			{
				if ((this._VALUTA != value))
				{
					this._VALUTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SasNaStDate", DbType="Date")]
		public System.Nullable<System.DateTime> SasNaStDate
		{
			get
			{
				return this._SasNaStDate;
			}
			set
			{
				if ((this._SasNaStDate != value))
				{
					this._SasNaStDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Compani", DbType="Int")]
		public System.Nullable<int> Compani
		{
			get
			{
				return this._Compani;
			}
			set
			{
				if ((this._Compani != value))
				{
					this._Compani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="Int")]
		public System.Nullable<int> User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
	
	public partial class AngResult
	{
		
		private int _ID;
		
		private int _PID;
		
		private int _DONE;
		
		private string _ANGNOM;
		
		private string _ANDDAS;
		
		public AngResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="Int NOT NULL")]
		public int PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this._PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONE", DbType="Int NOT NULL")]
		public int DONE
		{
			get
			{
				return this._DONE;
			}
			set
			{
				if ((this._DONE != value))
				{
					this._DONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANGNOM", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANGNOM
		{
			get
			{
				return this._ANGNOM;
			}
			set
			{
				if ((this._ANGNOM != value))
				{
					this._ANGNOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANDDAS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ANDDAS
		{
			get
			{
				return this._ANDDAS;
			}
			set
			{
				if ((this._ANDDAS != value))
				{
					this._ANDDAS = value;
				}
			}
		}
	}
	
	public partial class _BugGatResult
	{
		
		private int _Id;
		
		private bool _Dadasturebuli;
		
		private bool _Gadadebuli;
		
		private int _DokTipi;
		
		private int _DokNom;
		
		private int _DokNom1;
		
		private string _Debang;
		
		private string _DebDas;
		
		private string _kredang;
		
		private string _kreddas;
		
		private System.Nullable<int> _Tanxa;
		
		private string _Valuta;
		
		private double _Kursi;
		
		private System.Nullable<int> _Memoriali;
		
		private string _Safudzveli;
		
		private string _AnalizuriVeli;
		
		private System.DateTime _ShesrulebisTarigi;
		
		private int _company;
		
		private int _Shemsrulebeli;
		
		public _BugGatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dadasturebuli", DbType="Bit NOT NULL")]
		public bool Dadasturebuli
		{
			get
			{
				return this._Dadasturebuli;
			}
			set
			{
				if ((this._Dadasturebuli != value))
				{
					this._Dadasturebuli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gadadebuli", DbType="Bit NOT NULL")]
		public bool Gadadebuli
		{
			get
			{
				return this._Gadadebuli;
			}
			set
			{
				if ((this._Gadadebuli != value))
				{
					this._Gadadebuli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DokTipi", DbType="Int NOT NULL")]
		public int DokTipi
		{
			get
			{
				return this._DokTipi;
			}
			set
			{
				if ((this._DokTipi != value))
				{
					this._DokTipi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DokNom", DbType="Int NOT NULL")]
		public int DokNom
		{
			get
			{
				return this._DokNom;
			}
			set
			{
				if ((this._DokNom != value))
				{
					this._DokNom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DokNom1", DbType="Int NOT NULL")]
		public int DokNom1
		{
			get
			{
				return this._DokNom1;
			}
			set
			{
				if ((this._DokNom1 != value))
				{
					this._DokNom1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Debang
		{
			get
			{
				return this._Debang;
			}
			set
			{
				if ((this._Debang != value))
				{
					this._Debang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebDas", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DebDas
		{
			get
			{
				return this._DebDas;
			}
			set
			{
				if ((this._DebDas != value))
				{
					this._DebDas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kredang", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kredang
		{
			get
			{
				return this._kredang;
			}
			set
			{
				if ((this._kredang != value))
				{
					this._kredang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kreddas", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kreddas
		{
			get
			{
				return this._kreddas;
			}
			set
			{
				if ((this._kreddas != value))
				{
					this._kreddas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanxa", DbType="Int")]
		public System.Nullable<int> Tanxa
		{
			get
			{
				return this._Tanxa;
			}
			set
			{
				if ((this._Tanxa != value))
				{
					this._Tanxa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Valuta
		{
			get
			{
				return this._Valuta;
			}
			set
			{
				if ((this._Valuta != value))
				{
					this._Valuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kursi", DbType="Float NOT NULL")]
		public double Kursi
		{
			get
			{
				return this._Kursi;
			}
			set
			{
				if ((this._Kursi != value))
				{
					this._Kursi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memoriali", DbType="Int")]
		public System.Nullable<int> Memoriali
		{
			get
			{
				return this._Memoriali;
			}
			set
			{
				if ((this._Memoriali != value))
				{
					this._Memoriali = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Safudzveli", DbType="NVarChar(1000)")]
		public string Safudzveli
		{
			get
			{
				return this._Safudzveli;
			}
			set
			{
				if ((this._Safudzveli != value))
				{
					this._Safudzveli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalizuriVeli", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AnalizuriVeli
		{
			get
			{
				return this._AnalizuriVeli;
			}
			set
			{
				if ((this._AnalizuriVeli != value))
				{
					this._AnalizuriVeli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShesrulebisTarigi", DbType="Date NOT NULL")]
		public System.DateTime ShesrulebisTarigi
		{
			get
			{
				return this._ShesrulebisTarigi;
			}
			set
			{
				if ((this._ShesrulebisTarigi != value))
				{
					this._ShesrulebisTarigi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="Int NOT NULL")]
		public int company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this._company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shemsrulebeli", DbType="Int NOT NULL")]
		public int Shemsrulebeli
		{
			get
			{
				return this._Shemsrulebeli;
			}
			set
			{
				if ((this._Shemsrulebeli != value))
				{
					this._Shemsrulebeli = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
